// <auto-generated />
using System;
using Biblioteca.Biblioteca.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Api.Migraciones.Biblioteca
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20261004162617_CatalogoSociosEjemplares")]
    partial class CatalogoSociosEjemplares
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Biblioteca.Catalogo.Ejemplar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("IngresadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Retirado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ejemplar_Codigo");

                    b.HasIndex("RecursoId");

                    b.ToTable("Ejemplar", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Catalogo.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<short?>("AnioPublicacion")
                        .HasColumnType("smallint");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Editorial")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Genero")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasDatabaseName("UQ_Recurso_Isbn")
                        .HasFilter("[Isbn] IS NOT NULL");

                    b.ToTable("Recurso", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Prestamos.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EjemplarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EntregadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaLimite")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motivo")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset?>("ResueltoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SolicitadoEn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prestamo_EjemplarVivo")
                        .HasFilter("[Estado] IN ('Solicitado','Activo')");

                    b.HasIndex("EjemplarId", "Estado");

                    b.HasIndex("SocioId", "Estado");

                    b.ToTable("Prestamo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prestamo_Estado", "Estado IN ('Solicitado','Activo','Devuelto','Rechazado','Perdido')");
                        });
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Socios.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AltaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("LimitePrestamosSimultaneos")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LimitePrestamosVencidos")
                        .HasColumnType("tinyint");

                    b.Property<string>("NumeroSocio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSocio")
                        .IsUnique()
                        .HasDatabaseName("UQ_Socio_NumeroSocio");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Socio_UsuarioId");

                    b.ToTable("Socio", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Catalogo.Ejemplar", b =>
                {
                    b.HasOne("Biblioteca.Biblioteca.Catalogo.Recurso", "Recurso")
                        .WithMany("Ejemplares")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Prestamos.Prestamo", b =>
                {
                    b.HasOne("Biblioteca.Biblioteca.Catalogo.Ejemplar", "Ejemplar")
                        .WithMany("Prestamos")
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Biblioteca.Socios.Socio", "Socio")
                        .WithMany("Prestamos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Catalogo.Ejemplar", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Catalogo.Recurso", b =>
                {
                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("Biblioteca.Biblioteca.Socios.Socio", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
