// <auto-generated />
using System;
using Biblioteca.Biblioteca.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Api.Migraciones.Biblioteca
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20261004052309_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Biblioteca.Prestamos.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EjemplarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EntregadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaLimite")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Motivo")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset?>("ResueltoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SolicitadoEn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prestamo_EjemplarVivo")
                        .HasFilter("[Estado] IN ('Solicitado','Activo')");

                    b.HasIndex("EjemplarId", "Estado");

                    b.HasIndex("SocioId", "Estado");

                    b.ToTable("Prestamo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prestamo_Estado", "Estado IN ('Solicitado','Activo','Devuelto','Rechazado','Perdido')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
