// <auto-generated />
using System;
using Biblioteca.Identidad.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Api.Migraciones.Identidad
{
    [DbContext(typeof(IdentidadDbContext))]
    [Migration("20261004052233_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.CodigoRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("EmitidoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("VenceEn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CodigoHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_CodigoRecuperacion_CodigoHash");

                    b.HasIndex("UsuarioId", "UsadoEn");

                    b.ToTable("CodigoRecuperacion", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MotivoCierre")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sesion_TokenHash");

                    b.HasIndex("UsuarioId", "CerradaEn");

                    b.ToTable("Sesion", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.TokenActivacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EmitidoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("VenceEn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_TokenActivacion_TokenHash");

                    b.HasIndex("UsuarioId", "UsadoEn");

                    b.ToTable("TokenActivacion", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("PasswordCambiadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BloqueadoHasta");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Correo");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.CodigoRecuperacion", b =>
                {
                    b.HasOne("Biblioteca.Identidad.Entidades.Usuario", "Usuario")
                        .WithMany("CodigosRecuperacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.Sesion", b =>
                {
                    b.HasOne("Biblioteca.Identidad.Entidades.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.TokenActivacion", b =>
                {
                    b.HasOne("Biblioteca.Identidad.Entidades.Usuario", "Usuario")
                        .WithMany("TokensActivacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Biblioteca.Identidad.Entidades.Usuario", b =>
                {
                    b.Navigation("CodigosRecuperacion");

                    b.Navigation("Sesiones");

                    b.Navigation("TokensActivacion");
                });
#pragma warning restore 612, 618
        }
    }
}
